config/routes.rb
Rails.application.routes.draw do

  resources :artists do
  resources :songs
end
  get 'pages/home'
  root to: 'pages#home'

  namespace :api do
    resources :artists do
      resources :songs
      delete '/songs', to: 'songs#destroy_all'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
has_many :songs, dependent: :destroy
has_one :photo, dependent: :destroy

validates :name, presence: true
validates :bio, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :artist

  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord

  belongs_to :artist

  validates :name, presence: true

end

app/controllers/api/songs_controller.rb
class Api::SongsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    render status: 200, json: {
      songs: Song.all
    }.to_json
  end

  def create
    artist = Artist.find(params[:artist_id])
    song = artist.songs.new(song_params)

    if song.save
     render status: 200, json: {
       message: "Song successfully created",
       song: song,
     }.to_json
    else
      render status: 422, json: {
        errors: song.errors
      }.to_json
    end
  end

  def destroy
    @song=Song.find(params[:id])
    if @song.destroy
    render status: 200, json: {
      message: "Song was successfully removed"
    }.to_json
  else
    render status: 422, json: {
      message: "fku"
    }.to_json
  end
  end

  def destroy_all
    artist = Artist.find(params[:artist_id])
    songs = artist.songs
    songs.destroy_all

    render status: 200, json: {
      message: "All songs gone :("
    }.to_json
  end


  private
  def song_params
      params.permit(:name, :artist_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
    @photo = Photo.first
  end

  def contact;
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def new
    @artist = Artist.new
  end

  def songs
    @songs = @artist.songs
  end

  def destroy
    @artist=Artist.find(params[:id])
    @artist.destroy
    redirect_to artists_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def new
    @song = Song.new
  end

  def index
    @songs = @artist.songs
    @song = Song.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new(song_params)

    if @song.save
      redirect_to @artist, notice: "You have added a song to the artist"
    else
      render :new
    end
  end

  def destroy
    @song=Song.find(params[:id])
    @song.destroy
    redirect_to root_path
  end

  private

  def song_params
      params.require(:song).permit(:name, :artist_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist, html: { multipart: true } do |f|  %>

 <div class="form-group">
     <%= f.label :name %>
     <%= f.text_field :name %>
 </div>
 <div class="form-group">
     <%= f.label :country %>
     <%= f.text_field :country %>
 </div>

 <button><%= f.submit "Submit" %></button>

<%end%>

app/views/artists/index.html.erb
<h1>
<h1 style="text-align: center;">Artists</h1>
</h1>
</br>
<% @artists.each do |artist| %>
  <h2 style="text-align: center;"><%= link_to artist.name, artist_path(artist.id) %></h2>


</br>

  <div id="ImageContainer">
  <p><%= image_tag artist.photo.image_url %> </p>
</div>
<% end %>

app/views/artists/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new song
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/artists/show.html.erb
<div class="artshow" style="text-align: center;">

  <h4> Artist </h4>
<p><h1><%=@artist.name%></h1></p>
<p>Formed in: <b><%=@artist.act_since%></b> Genre(s): <%=@artist.genre%></p>
<hr>
<h4>Songs:</h4>
<ul id="songs-list">
  <% @artist.songs.each do |song| %>
    <li data-id="<%= song.id %>"><%= song.name %><button class="delete-button">x</button></li>
  <% end %>
</ul>
<hr>
<button type="button" id="delete-all" >Delete all songs</button>
</div>

<p>Bio: <%=@artist.bio%></p>

<hr>

<div id="delete-artist"><%= link_to "Remove this artist", artist_path(@artist[:id]), method: :delete %></div>

<form onSubmit="submitSong(event)">
  <label for="song-input">Add a new Song</label>
  <input type="text" id="song-input">
</form>
<script>
  var artistId = <%= @artist.id %>;
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>

    <!-- <link rel="icon" href="https://www.codaisseur.com/assets/webpack-assets/codaisseur-logo-colore1b2f1695e1af08537a8ccb15598cf7f.svg"> -->
  </head>

  <body>
  <%= render "shared/navbar" %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
  </div>
  <%= javascript_include_tag 'application' %>
</body>

</html>

app/views/pages/contact.html.erb
<h1>Waddup</h1>

app/views/pages/home.html.erb
<div style="text-align: center;">
<h1>Codaisseurify</h1>
<hr>
<h4>Helping you find your artists</h4>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


<h4>Visit our <%= link_to "Artists", artists_path %></h4>

</div>

app/views/shared/_navbar.html.erb
    </nav> -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
      <%= link_to "Codaisseurify", root_path, class: "navbar-brand" %>
        </div>
        <div class="d-flex justify-content-around">
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
             <!-- <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            </div> -->

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/songs/_form.html.erb
<div class="ding" style="text-align: center;">
<%= form_for @song, :url => { :action => "create"} do |f|  %>

 <div class="form-group">
     <%= f.label :name %>
     <%= f.text_field :name %>
 </div>
 <div class="form-group">
     <%= f.label :Min %>
     <%= f.number_field :length_min %>

     <%= f.label :Sec %>
     <%= f.number_field :length_sec %>
 </div>
 <div>
 <%= f.label :artist_id %>
   <%= f.collection_select(:artist_id, Artist.all, :id, :name) %>
</div>
   <div class="actions">
  <%= f.submit "Save", class: "btn btn-success" %>
</div>
<%end%>
</div>

<%= link_to "Back", artists_path, class: "btn btn-default" %>

app/views/songs/destroy.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Delete a song
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/songs/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="page-header">Songs</h1>

    <% if notice.present? %>
      <div class="alert alert-info" role="alert">
        <%= notice %>
      </div>
    <% end %>

    <%= render "form", song: @song %>

    <hr />

    <table class="table table-striped" id="todoList">
      <%= render @songs %>
    </table>
  </div>
</div>

app/views/songs/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new song
  </div>

  <div class="panel-body">
 <%= form_for [:artist, @song] do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div class="form-group">
        <%= f.label :Min %>
        <%= f.number_field :length_min %>

        <%= f.label :Sec %>
        <%= f.number_field :length_sec %>
    </div>
    <div class="actions">
   <%= f.submit "Save", class: "btn btn-success" %>
 </div>
    <% end %>
  </div>
</div>